"""add email to users

Revision ID: 1023de83d81b
Revises: f3a1550af694
Create Date: 2026-03-07 11:45:08.768076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1023de83d81b'
down_revision: Union[str, Sequence[str], None] = 'f3a1550af694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('file_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'type',
               existing_type=postgresql.ENUM('text', 'image', 'file', name='messagetype'),
               type_=sa.Enum('text', 'image', 'file', name='message_type'),
               existing_nullable=False)
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('uploading', 'success', 'error', name='messagestatus'),
               nullable=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_type')
    op.add_column('users', sa.Column('max_quota_bytes', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('used_quota_bytes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['github_id'])
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email')
    op.drop_column('users', 'used_quota_bytes')
    op.drop_column('users', 'max_quota_bytes')
    op.add_column('messages', sa.Column('file_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.alter_column('messages', 'status',
               existing_type=postgresql.ENUM('uploading', 'success', 'error', name='messagestatus'),
               nullable=True)
    op.alter_column('messages', 'type',
               existing_type=sa.Enum('text', 'image', 'file', name='message_type'),
               type_=postgresql.ENUM('text', 'image', 'file', name='messagetype'),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('messages', 'original_filename')
    op.drop_column('messages', 'file_size_bytes')
    op.drop_column('messages', 'file_id')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'mime_type')
    op.drop_column('messages', 'is_deleted')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
